### ISSUE TITLE
only Import components you need from react-stoon

### ISSUE THREAD

**Issue by bigfanjs** [MoroccanOSS/react-stoon#2]
We know generalized imports blow bundle sizes and increase the script evaluation and compilation time. So, In this issue I am requesting a new **feature** which helps you specify only the components you need to import.
```js
import Show from "react-stoon/Show";
import Repeat from "react-stoon/Repeat";
```
I think we still end up loading some useless code even with module bundlers like Webpack's best optimization tricks like taking down dead code using _tree shaking_ before we load our code to the browser. But because most of EcmaScript latest features are now available natively in the some browsers. Some people may not even bother bundling up their code and directly start importing their modules.

```html
<script type="module" src="./script.js"></script>
```

I thought I would issue this before I start working on it.

**Comment by Amine-H** [comment]
Hello,
you are right, I'd like to comment on this, we could make each component in a separate module and load all of them into index.js

that way we could do either:
```jsx
import { Show } from '@moroccan-oss/react-stoon';
```
and for who ever wants optimized builds:
```jsx
import Show from '@moroccan-oss/react-stoon/Show';
```
